// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApz7xUm9Pc4MAVDtxWqUZY9E-aZoZA0HI',
    appId: '1:589265508739:web:138da2c4e437f3f0d07eb6',
    messagingSenderId: '589265508739',
    projectId: 'arogyasathi-7f2c1',
    authDomain: 'arogyasathi-7f2c1.firebaseapp.com',
    storageBucket: 'arogyasathi-7f2c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFjYgUXLkj9QtnhmsY8wtyEPPw_lRRphg',
    appId: '1:589265508739:android:5895db23d9dc4893d07eb6',
    messagingSenderId: '589265508739',
    projectId: 'arogyasathi-7f2c1',
    storageBucket: 'arogyasathi-7f2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaf_jQtZFji7pgscd9j8sSVEhvpsY0Ffg',
    appId: '1:589265508739:ios:b7c958fbb37bd96cd07eb6',
    messagingSenderId: '589265508739',
    projectId: 'arogyasathi-7f2c1',
    storageBucket: 'arogyasathi-7f2c1.firebasestorage.app',
    iosBundleId: 'com.example.arogyasathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaf_jQtZFji7pgscd9j8sSVEhvpsY0Ffg',
    appId: '1:589265508739:ios:b7c958fbb37bd96cd07eb6',
    messagingSenderId: '589265508739',
    projectId: 'arogyasathi-7f2c1',
    storageBucket: 'arogyasathi-7f2c1.firebasestorage.app',
    iosBundleId: 'com.example.arogyasathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApz7xUm9Pc4MAVDtxWqUZY9E-aZoZA0HI',
    appId: '1:589265508739:web:7e6f1b130aacbee6d07eb6',
    messagingSenderId: '589265508739',
    projectId: 'arogyasathi-7f2c1',
    authDomain: 'arogyasathi-7f2c1.firebaseapp.com',
    storageBucket: 'arogyasathi-7f2c1.firebasestorage.app',
  );
}
